### ISSUE TITLE
mảng số thực nhá em

### ISSUE THREAD

**Issue by linhnd99** [caothethang/caothethang_BTVN-Java#1]
https://github.com/caothethang/caothethang_BTVN-Java/blob/24491b2858706f4c6ce2e059edd7c9cdc4705760/Buoi4_Ktra/src/Ktra/Bai2.java#L71

**Comment by caothethang** [comment]
đề bài là mảng số thực à anh

**Comment by linhnd99** [comment]
đề bài ko nói gì tức là trường hợp số thực vẫn có thể xảy ra
